[package]
name = "josh-ssh-shell"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "4.0.25", features = ["derive", "help", "std", "usage"], default-features = false }
libc = "0.2.134"
rand = "0.8.5"
shell-words = "1.1.0"
tokio = { version = "1.21.2", features = ["fs", "rt-multi-thread", "macros", "io-std", "io-util", "net"] }
reqwest = { version = "0.11.12", features = ["json"] }
josh-rpc = { path = "../josh-rpc" }
serde_json = "1.0.86"
tracing = { version = "0.1.36", features = ["max_level_trace", "release_max_level_trace"] }
tracing-futures = "0.2.5"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
tokio-util = "0.7.4"
thiserror = "1.0.37"
