[package]
name = "josh-ssh-shell"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
libc = { workspace = true }
shell-words = "1.1.1"
tokio = { workspace = true }
josh-rpc = { path = "../josh-rpc" }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio-util = { workspace = true }
thiserror = "2.0.18"
tempfile = { workspace = true }
reqwest = { workspace = true }

[features]
incubating = []
