[package]
name = "josh-ssh-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
libc = { workspace = true }
shell-words = "1.1.0"
tokio = { workspace = true }
josh-rpc = { path = "../josh-rpc" }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio-util = { workspace = true }
thiserror = "1.0.49"
tempfile = "3.8.0"
reqwest = { workspace = true }
