[package]
name = "josh-ssh-shell"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "4.1.6", features = ["derive", "help", "std", "usage"], default-features = false }
libc = "0.2.139"
shell-words = "1.1.0"
tokio = { version = "1.26.0", features = ["fs", "rt-multi-thread", "macros", "io-std", "io-util", "net"] }
josh-rpc = { path = "../josh-rpc" }
serde_json = "1.0.93"
tracing = { version = "0.1.37", features = ["max_level_trace", "release_max_level_trace"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tokio-util = "0.7.7"
thiserror = "1.0.38"
tempfile = "3.3.0"

[dependencies.reqwest]
default-features = false
version = "0.11.14"
features = ["json"]
