[package]
name = "josh"
version = "25.11.26"
edition = "2024"

repository = "https://github.com/josh-project/josh"
authors = ["Christian Schilling <christian.schilling@esrlabs.com>"]
license-file = "../LICENSE"
description = "CLI interface for josh"
readme = "../README.md"
keywords = ["git", "monorepo", "workflow", "scm"]

[dependencies]
josh-core = { workspace = true }
anyhow = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
defer = { workspace = true }
clap = { workspace = true }
rs_tracing = { workspace = true }
juniper = { workspace = true }
git2 = { workspace = true }
toml = { workspace = true }

[features]
incubating = []
