[package]
name = "josh-github-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
http.workspace = true
reqwest.workspace = true
reqwest-middleware.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["time"] }
tracing.workspace = true
mime.workspace = true
form_urlencoded.workspace = true
url.workspace = true

secret-vault-value = "^1"
jsonwebtoken.workspace = true
chrono.workspace = true

[dev-dependencies]
tokio.workspace = true
tracing-subscriber.workspace = true
