[package]
name = "josh-ui"
version = "0.1.0"
authors = ["Christian Schilling <christian.schilling.de@gmail.com"]
edition = "2018"

[dependencies]

wasm-bindgen = "0.2"
yew = "*"
yew-router = "*"
js-sys = "*"
anyhow = "*"
serde_json= "*"
serde= "*"
graphql_client = "*"

