[package]
name = "josh-filter"
version = "25.11.24"
edition = "2024"

repository = "https://github.com/josh-project/josh"
authors = ["Christian Schilling <initcrash@gmail.com>"]
license-file = "../LICENSE"
description = "Low-level CLI interface for local Josh use"
keywords = ["git", "monorepo", "workflow", "scm"]
readme = "../README.md"

[dependencies]
josh-core = { workspace = true }
josh-graphql = { workspace = true }
josh-templates = { workspace = true }
env_logger = { workspace = true }
serde_json = { workspace = true }
defer = { workspace = true }
clap = { workspace = true }
rs_tracing = { workspace = true }
juniper = { workspace = true }
git2 = { workspace = true }

[features]
incubating = []
