[package]
name = "josh-rpc"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.152", features = ["std", "derive"] }
tokio = { version = "1.26.0", features = ["fs", "io-std"] }
libc = "0.2.139"
