[package]
name = "josh-link"
version = "0.1.0"
edition = "2024"

[dependencies]
josh-core = { path = "../josh-core", features = ["incubating"] }
git2 = { workspace = true }
anyhow = { workspace = true }
