[package]
name = "josh"
version = "22.4.15"
repository = "https://ithub.com/josh-project/josh"
authors = ["Christian Schilling <initcrash@gmail.com>"]
license-file = "LICENSE"
description = "GIT virtualization proxy"
keywords = ["git", "monorepo", "workflow", "scm"]
readme = "README.md"
edition = "2021"

[dependencies]
backtrace = "0.3.69"
bitvec = "1.0.1"
git-version = "0.3.9"
git2 = { workspace = true }
glob = "0.3.1"
handlebars = "5.1.0"
hex = "0.4.3"
indoc = "2.0.4"
itertools = "0.11.0"
lazy_static = { workspace = true }
log = "0.4.21"
percent-encoding = "2.3.1"
pest = "2.7.8"
pest_derive = "2.7.8"
rayon = "1.9.0"
regex = { workspace = true }
rs_tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sled = "0.34.7"
strfmt = "0.2.4"
toml = { workspace = true }
tracing = { workspace = true }
gix = { workspace = true }
juniper = { workspace = true }

[dependencies.chrono]
default-features = false
features = ["alloc", "std"]
version = "0.4.35"
