[package]
name = "josh"
version = "22.4.15"
repository = "https://ithub.com/josh-project/josh"
authors = ["Christian Schilling <initcrash@gmail.com>"]
license-file = "LICENSE"
description = "GIT virtualization proxy"
keywords = ["git", "monorepo", "workflow", "scm"]
readme = "../README.md"
edition = "2024"

[dependencies]
backtrace = "0.3.76"
bitvec = "1.0.1"
git-version = "0.3.9"
git2 = { workspace = true }
gix-object = "0.50.2"
glob = "0.3.1"
hex = { workspace = true }
indoc = "2.0.7"
itertools = "0.14.0"
lazy_static = { workspace = true }
log = "0.4.28"
percent-encoding = "2.3.1"
pest = "2.8.3"
pest_derive = "2.8.3"
rayon = "1.11.0"
regex = { workspace = true }
rs_tracing = { workspace = true }
strfmt = "0.2.4"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sled = "0.34.7"
tracing = { workspace = true }
